# Generated by Django 4.2.1 on 2023-05-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_alter_sexo_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='clientes',
        ),
    ]
