# Generated by Django 4.2.1 on 2023-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_rename_cliente_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.TextField(max_length=50),
        ),
    ]
