# Generated by Django 4.2.1 on 2023-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_alter_clientes_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientes',
            name='firstname',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.TextField(default='', max_length=255),
        ),
    ]
