# Generated by Django 4.2.1 on 2023-05-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_alter_clientes_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sexo',
            old_name='description',
            new_name='descricao',
        ),
    ]
