# Generated by Django 4.2.1 on 2023-05-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0013_alter_sexo_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='firstname',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='password',
            new_name='senha',
        ),
    ]
