# Generated by Django 4.2.1 on 2023-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_rename_firstname_clientes_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexo',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
