# Generated by Django 4.2.1 on 2023-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0015_alter_sexo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.IntegerField(max_length=50),
        ),
    ]
