# Generated by Django 4.2.1 on 2023-05-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0016_alter_clientes_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='senha',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.IntegerField(),
        ),
    ]
