# Generated by Django 4.2.1 on 2023-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0018_user_id_cliente_alter_clientes_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='senha',
            field=models.CharField(default=12345, max_length=255),
        ),
    ]
