# Generated by Django 4.2.1 on 2023-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0020_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.IntegerField(),
        ),
    ]
