# Generated by Django 4.2.1 on 2023-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0026_alter_user_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
