# Generated by Django 4.2.1 on 2023-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0027_alter_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='historias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('previa', models.CharField(max_length=50)),
                ('texto_completo', models.TextField()),
            ],
        ),
    ]
