# Generated by Django 4.2.1 on 2023-05-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0028_categoria_historia_historias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historias',
            old_name='previa',
            new_name='titulo',
        ),
    ]
